### ISSUE TITLE
All day events

### ISSUE THREAD

**Issue by seler** [Yoone/rsi-schedule#1]
Most of events are showing up as 2 hour slots that start at 12:00 UTC where in fact these are more like a points in time. I suggest that these are all-day events.

Example code:
DTSTART;VALUE=DATE:20170316
DTEND;VALUE=DATE:20170316

**Comment by Yoone** [comment]
Thanks for the interest!

I agree, this might be better and would interfere less with events during the day. Do you wish to make a pull request?
